In [2]:
import pandas as pd
print(pd.__version__)

2.3.3


In [3]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','f'])
s

a    1
b    2
c    3
d    4
f    5
dtype: int64

In [4]:
s.values

array([1, 2, 3, 4, 5])

In [5]:
s.index

Index(['a', 'b', 'c', 'd', 'f'], dtype='object')

In [6]:
type(s)

pandas.core.series.Series

In [7]:
type(s.values)

numpy.ndarray

In [10]:
s[1]

C:\Users\a.gutierrez\AppData\Local\Temp\ipykernel_1168\878419959.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]


np.int64(2)

In [9]:
s['b']

np.int64(2)

In [11]:
s['b':'d']

b    2
c    3
d    4
dtype: int64

In [12]:
s[1:3]

b    2
c    3
dtype: int64

In [14]:
serie1 = pd.Series({'a': 78, 'b': 79, 'c': 80})
serie1

a    78
b    79
c    80
dtype: int64

In [15]:
serie1.values

array([78, 79, 80])

In [16]:
serie1.index

Index(['a', 'b', 'c'], dtype='object')

In [22]:
serie2 = pd.Series({'a': 10, 'b': 11, 'c': 12})
serie2

a    10
b    11
c    12
dtype: int64

In [23]:
dataframe1 = pd.DataFrame({'Serie 1': serie1, 'Serie 2': serie2})
dataframe1

Serie 1  Serie 2
a       78       10
b       79       11
c       80       12

In [26]:
dataframe1.T

a   b   c
Serie 1  78  79  80
Serie 2  10  11  12

In [30]:
dataframe1.values

array([[78, 10],
       [79, 11],
       [80, 12]])

In [31]:
dataframe1.index

Index(['a', 'b', 'c'], dtype='object')

In [32]:
dataframe1.columns

Index(['Serie 1', 'Serie 2'], dtype='object')

In [34]:
dataframe1.values[1,0]

np.int64(79)

In [35]:
dataframe1

Serie 1  Serie 2
a       78       10
b       79       11
c       80       12

In [37]:
dataframe1['Total Series'] = dataframe1['Serie 1'] + dataframe1['Serie 2']
dataframe1

Serie 1  Serie 2  Total Series
a       78       10            88
b       79       11            90
c       80       12            92

In [38]:
dataframe1

Serie 1  Serie 2  Total Series
a       78       10            88
b       79       11            90
c       80       12            92

In [39]:
del dataframe1['Total Series']
dataframe1

Serie 1  Serie 2
a       78       10
b       79       11
c       80       12

In [40]:
dataframe1.loc['a']

Serie 1    78
Serie 2    10
Name: a, dtype: int64

In [42]:
dataframe1.loc[['a','c','b']]

Serie 1  Serie 2
a       78       10
c       80       12
b       79       11

In [44]:
dataframe1.iloc[0]

Serie 1    78
Serie 2    10
Name: a, dtype: int64

In [45]:
dataframeSearch = dataframe1[dataframe1['Serie 1'] >= 79]
dataframeSearch

Serie 1  Serie 2
b       79       11
c       80       12